version: '3'
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRESS_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
