version: '3.8'

services:
  client:
    image: "gahamanyi/frontend:latest"
    mem_limit: 128m
    hostname: frontend
  server:
    image: "gahamanyi/backend:latest"
    mem_limit: 128m
    hostname: backend
  nginx:
    image: "gahamanyi/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"